### Create a new mobile if the user is logged in
POST http://localhost:3000/mobiles/create
Content-Type: application/json

{
  "name": "Huawei",
  "brand": "Huawei",
  "specs": "Very excellent phone",
  "year": 2016,
  "price": 10340,
  "categories": [ "private"]
}

### Get all listings in a category. A registered user can call both categories
### while a unregistered user can only see public listings
Get http://localhost:3000/mobiles/getCategoryMobiles/private


### Get a user's mobiles if they are logged in
Get http://localhost:3000/mobiles/myMobiles



#### Delete a particular mobile if a user is logged in
PATCH  http://localhost:3000/mobiles/deleteMobile/Huawei
