POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "name": "Omer Ihtizaz", 
    "email": "Omerasd@gmail.com",
    "password": "Oasdmer",
    "admin": 0
}

###
POST http://localhost:3000/users/signin
Content-Type: application/json

{
    "email": "Omerasd@gmail.com",
    "password": "Oasdmer"
}

###
Post http://localhost:3000/users/logout
####
# ###
# Get http://localhost:3000/users/colors/Red
# ####
# Get  http://localhost:3000/users/getColors
###

Get http://localhost:3000/users/whoami
####
Get http://localhost:3000/users/findOne/1


###
Get http://localhost:3000/users/find/Omer@gmail.com


###
PATCH  http://localhost:3000/users/update/6
Content-Type: application/json

{
    "email":"ahmed.tariq@hotmail.com"
}


### 
Get http://localhost:3000/users/remove/3