POST http://localhost:3000/admin/signup
Content-Type: application/json

{
    "name": "Admin", 
    "email": "Admin@gmail.com",
    "password": "Admin",
    "admin": 1
}

###
POST http://localhost:3000/admin/signin
Content-Type: application/json

{
    "email": "Admin@gmail.com",
    "password": "Admin"
}


### 
Get http://localhost:3000/admin/blacklist/admin3@gmail.com


### 
Get http://localhost:3000/admin/whitelist/admin3@gmail.com